## Provide all values as percentages
TestEnv:
        percentage:
                 50 ## The percentage of test cases to be passed at Jenkins Server.
PreProdEnv:
        percentage:
                 80 ## The percentage of test cases to be passed at Test ENV.
ProdEnv:
        percentage:
                100 ## The percentage of test cases to be passed at Prod Env.
                
                
